const SHAPE3 = [
  ["box", "Quader"],
  ["cyl", "Zylinder"],
  ["cone", "Kegel"],
  ["sphere", "Kugel"],
  ["prism", "Prisma"],
  ["torus", "Torus"],
  ["capsule", "Kapsel"],
  ["wedge", "Keil"],
  ["arch", "Bogen"],
  ["plane", "Ebene"],
  ["pyramid", "Pyramide"],
  ["dome", "Kuppel"],
  ["tube", "Rohr"],
  ["oct", "Achteck"],
  ["stairs", "Treppe"],
  ["gable", "Satteldach"],
  ["bowl", "Schale"],
  ["ring", "Ring"],
  ["post", "Pfosten"],
  ["beam", "Balken"],
  ["slab", "Platte"],
  ["tent", "Zelt"],
  ["silo", "Silo"],
  ["trough", "Trog"],
  ["ramp", "Rampe"],
  ["hip", "Walmdach"],
  ["barrel", "Fass"],
  ["helix", "Wendel"],
  ["basin", "Becken"],
  ["frame", "Rahmen"],
  ["pergola", "Pergola"],
  ["hoop", "Tunnelbogen"],
  ["lblock", "L-Stein"],
  ["disc", "Scheibe"],
  ["well", "Brunnen"],
  ["crate", "Kiste"],
];

const MAT3 = [
  ["holz", "Holz"],
  ["metall", "Metall"],
  ["stein", "Stein"],
  ["glas", "Glas"],
  ["erde", "Erde"],
  ["kunststoff", "Kunststoff"],
  ["ziegel", "Ziegel"],
  ["beton", "Beton"],
  ["lehm", "Lehm"],
  ["kies", "Kies"],
  ["wasser", "Wasser"],
  ["dach", "Dach"],
  ["folie", "Folie"],
  ["mulch", "Mulch"],
  ["kalk", "Kalk"],
  ["sand", "Sand"],
  ["corten", "Corten"],
  ["pflanz", "Pflanze"],
  ["asphalt", "Asphalt"],
  ["terracotta", "Terrakotta"],
  ["copper", "Kupfer"],
  ["thatch", "Reet"],
  ["moss", "Moos"],
  ["rubber", "Gummi"],
  ["weiss", "Weiß"],
];

function bit(send, label, action) {
  return { label, click: send(action) };
}

function sub(label, items) {
  return { label, submenu: items };
}

export function modellierenMenu(send) {
  return [
    bit(send, "Atelier ein/aus", "model3-bar"),
    { type: "separator" },
    sub("Werkzeug", [
      bit(send, "Drehen", "edit3-orbit"),
      bit(send, "Schieben", "edit3-move"),
      bit(send, "Heben", "edit3-lift"),
      bit(send, "Drehen 3D", "edit3-rot"),
      bit(send, "Skalieren", "edit3-scale"),
      bit(send, "Extrudieren", "edit3-extrude"),
      bit(send, "Ecken", "edit3-vert"),
      bit(send, "Maß 3D", "edit3-measure"),
      bit(send, "Gehen", "edit3-walk"),
      bit(send, "Fliegen", "edit3-fly"),
      bit(send, "Pflanze", "edit3-plant"),
    ]),
    sub("Körper zeichnen", SHAPE3.map(([id, lab]) => bit(send, `${lab} zeichnen`, `edit3-prim-${id}`))),
    sub("Form zuweisen", [
      ...SHAPE3.map(([id, lab]) => bit(send, `Als ${lab}`, `m3-${id}`)),
      bit(send, "Maße…", "prim3"),
      bit(send, "Form zurück", "m3-reset"),
    ]),
    sub("Maße & Höhe", [
      bit(send, "Höhe +10 cm", "m3-extrude"),
      bit(send, "Höhe −10 cm", "m3-press"),
      bit(send, "Anheben 10 cm", "elev+"),
      bit(send, "Absenken 10 cm", "elev-"),
      bit(send, "Sockel +50 cm", "m3-lift50"),
      bit(send, "Auf Gelände", "m3-ground"),
      bit(send, "Höhe Beet 30 cm", "m3-h:0.3"),
      bit(send, "Höhe Hochbeet 80 cm", "m3-h:0.8"),
      bit(send, "Höhe 1,2 m", "m3-h:1.2"),
      bit(send, "Höhe Haus 2,2 m", "m3-h:2.2"),
      bit(send, "Höhe 3,5 m", "m3-h:3.5"),
      bit(send, "Höhe Baum 5 m", "m3-h:5"),
      bit(send, "Taper 70 %", "m3-taper"),
      bit(send, "Taper 50 %", "m3-taper5"),
      bit(send, "Taper 85 %", "m3-taper8"),
      bit(send, "Taper zurück", "m3-taper0"),
      bit(send, "Fase", "m3-bevel"),
      bit(send, "Rundung", "m3-round"),
      bit(send, "Fase aus", "m3-bevel0"),
      bit(send, "Einzug", "m3-inset"),
      bit(send, "Ausdehnen", "m3-outset"),
      bit(send, "Auf Höhenmodell", "m3-to-hm"),
    ]),
    sub("Transformieren", [
      bit(send, "+15°", "m3-rot15"),
      bit(send, "−15°", "m3-rot-15"),
      bit(send, "+45°", "m3-rot45"),
      bit(send, "+90°", "m3-rot90"),
      bit(send, "−90°", "m3-rot-90"),
      bit(send, "Wenden", "m3-flip-x"),
      bit(send, "Spiegeln", "m3-flip-y"),
      bit(send, "Größer 10 %", "m3-scale-up"),
      bit(send, "Kleiner 10 %", "m3-scale-down"),
      bit(send, "Grundfläche +10 %", "m3-scale-xy"),
      bit(send, "Nur Höhe +10 %", "m3-scale-z"),
      bit(send, "Grundfläche −10 %", "m3-scale-xy-down"),
      bit(send, "10 cm Nord", "m3-nudge-n"),
      bit(send, "10 cm Süd", "m3-nudge-s"),
      bit(send, "10 cm Ost", "m3-nudge-e"),
      bit(send, "10 cm West", "m3-nudge-w"),
      bit(send, "Gleiche Höhe", "m3-equal-h"),
      bit(send, "Gleiche Grundfläche", "m3-equal-foot"),
      bit(send, "Links", "m3-align-w"),
      bit(send, "Rechts", "m3-align-e"),
      bit(send, "Unten", "m3-align-s"),
      bit(send, "Oben", "m3-align-n"),
      bit(send, "Mitte", "m3-align-c"),
      bit(send, "Teilen Ost/West", "m3-split-x"),
      bit(send, "Teilen Nord/Süd", "m3-split-y"),
      bit(send, "Raster 20 cm", "m3-snap"),
      bit(send, "Raster 50 cm", "m3-snap05"),
      bit(send, "Raster 10 cm", "m3-snap01"),
      bit(send, "Sperren", "m3-lock"),
      bit(send, "Freigeben", "m3-unlock"),
    ]),
    sub("Boolesch", [
      bit(send, "Vereinigen", "m3-union"),
      bit(send, "Differenz", "m3-cut"),
      bit(send, "Differenz umgekehrt", "m3-revcut"),
      bit(send, "Durchschnitt", "m3-intersect"),
      bit(send, "Aushöhlen", "m3-hollow"),
      bit(send, "Stapeln", "m3-stack"),
      bit(send, "Isolieren", "iso-sel"),
      bit(send, "Alles einblenden", "show-all"),
      bit(send, "Ausblenden", "m3-hide"),
      bit(send, "Einblenden", "m3-show"),
    ]),
    sub("Array & Spiegel", [
      bit(send, "Array 3×1", "m3-array-x"),
      bit(send, "Array 1×3", "m3-array-y"),
      bit(send, "Array 3×3", "m3-array-xy"),
      bit(send, "Reihe 5", "m3-array-5"),
      bit(send, "Stapel 3", "m3-array-z"),
      bit(send, "Polar 4", "m3-polar4"),
      bit(send, "Polar 6", "m3-polar"),
      bit(send, "Polar 8", "m3-polar8"),
      bit(send, "Polar 12", "m3-polar12"),
      bit(send, "Spiegel X", "m3-mirror-x"),
      bit(send, "Spiegel Y", "m3-mirror-y"),
      bit(send, "Kopie", "m3-dup3"),
    ]),
    sub("Dach", [
      bit(send, "Dach umschalten", "roof"),
      bit(send, "Flach", "m3-pitch:0"),
      bit(send, "18°", "m3-pitch:18"),
      bit(send, "32°", "m3-pitch:32"),
      bit(send, "45°", "m3-pitch:45"),
      bit(send, "Als Satteldach", "m3-gable"),
      bit(send, "Als Walmdach", "m3-hip"),
      bit(send, "Als Kuppel", "m3-dome"),
      bit(send, "Als Zelt", "m3-tent"),
    ]),
    sub("Material", MAT3.map(([id, lab]) => bit(send, lab, `m3-mat:${id}`))),
    sub("Gelände", [
      bit(send, "Formen", "edit3-sculpt"),
      bit(send, "Einebnen", "edit3-flatten"),
      bit(send, "Feld ebnen", "hm-flat"),
      bit(send, "Auf Höhenmodell", "m3-to-hm"),
      bit(send, "DGM importieren…", "dgm"),
      bit(send, "glTF exportieren…", "gltf"),
      bit(send, "glTF laden…", "gltf-in"),
    ]),
  ];
}

export const SHAPE3_LIST = SHAPE3;
